name: 'CI Slack Integration'
description: 'Post github event to slack'
author: sameer-cleartax
inputs:
  webhook:
    description: 'slack webhook url'
    required: true
  tag:
    description: 'tag slack group, enter comma separated slack id'
    required: false
runs:
  using: 'node16'
  main: ./dist/bot.js
