name: slack integration test
on:
  pull_request:
    types: [ opened, synchronize, reopened, edited ]
    branches: [ "main" ]
env:
  SLACK_WEBHOOK: https://hooks.slack.com/services/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

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: trying my shit
        uses: sameer-cleartax/slack-bot@main-clone
        with:
          webhook: ${{ env.SLACK_WEBHOOK }}
          tag: sameer.choudhary,sameer.choudhary
